### PR TITLE
Third party registry setup

### LINKED ISSUE #5: Use blocks from blockr.extra in registry

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Fix #5

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
@JohnCoene: can you confirm what block you need for the demo (i.e. do you still need all the demo blocks like `demo_arrange_block` or the outdated monolithic ggiraph/plot block)? Do you also need custom data blocks like:

```r
lab_data_block <- function(...) {
  initialize_block(new_data_block(
    ...,
    dat = as.environment("package:blockr.data"),
    selected = "lab"
  ))
}
```

For now, I included all of them except the one in #9.

**Comment by JohnCoene** [comment]
@DivadNojnarg I'm not doing the demo, @karmatarap is handling that, we can confirm with him but I do not think demo blocks are needed.

**Comment by JohnCoene** [comment]
@DivadNojnarg may we merge this?

**Comment by DivadNojnarg** [comment]
Yes I was checking the blocks. The plot_code_block will also suffer from the same issue we have in `{blockr}` (not for ggplot).

**Pull request merged**
